#!/usr/bin/env node
/**
 * Сканирует assets/club и assets/games
 * → js/generated/club-images.js
 *
 * window.CLUB_IMAGES — фото клуба (hero.* помечается isHero)
 * window.GAME_IMAGES — обложки игр (сопоставление по имени в main.js)
 *
 * Форматы: .jpg .jpeg .png .webp (любой регистр)
 * Имена: любые, кириллица и пробелы ок
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CLUB_DIR = path.join(ROOT, "assets", "club");
const GAMES_DIR = path.join(ROOT, "assets", "games");
const OUT_DIR = path.join(ROOT, "js", "generated");
const OUT_FILE = path.join(OUT_DIR, "club-images.js");
const EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function isImage(name) {
  return EXT.has(path.extname(name).toLowerCase());
}

function listImages(dir) {
  try {
    return fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((d) => d.isFile() && !d.name.startsWith(".") && isImage(d.name))
      .map((d) => d.name)
      .sort((a, b) => a.localeCompare(b, "ru", { sensitivity: "base" }));
  } catch (_) {
    return [];
  }
}

function toSrc(folder, filename) {
  return (
    "assets/" +
    folder +
    "/" +
    filename.split("/").map(encodeURIComponent).join("/")
  );
}

function isHeroName(name) {
  return path.parse(name).name.toLowerCase() === "hero";
}

function main() {
  fs.mkdirSync(CLUB_DIR, { recursive: true });
  fs.mkdirSync(GAMES_DIR, { recursive: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const clubFiles = listImages(CLUB_DIR);
  const gameFiles = listImages(GAMES_DIR);

  const clubImages = clubFiles.map((f) => ({
    file: f,
    src: toSrc("club", f),
    alt: "ZAGA GAME — фото клуба",
    isHero: isHeroName(f)
  }));

  const gameImages = gameFiles.map((f) => ({
    file: f,
    src: toSrc("games", f),
    // имя без расширения — для сопоставления с названием игры
    base: path.parse(f).name
  }));

  const body =
    "/* AUTO-GENERATED by scripts/generate-assets.js — не редактировать вручную */\n" +
    "window.CLUB_IMAGES = " +
    JSON.stringify(clubImages, null, 2) +
    ";\n" +
    "window.GAME_IMAGES = " +
    JSON.stringify(gameImages, null, 2) +
    ";\n";

  fs.writeFileSync(OUT_FILE, body, "utf8");

  const hero = clubImages.find((i) => i.isHero);
  console.log(
    "[generate-assets] club: " +
      clubImages.length +
      (hero ? " (hero: " + hero.file + ")" : " (no hero.*)")
  );
  clubImages.forEach((img) =>
    console.log("  club: " + img.file + (img.isHero ? " [HERO]" : ""))
  );
  console.log("[generate-assets] games: " + gameImages.length);
  gameImages.forEach((img) => console.log("  game: " + img.file));
}

main();
