#!/usr/bin/env node
/**
 * Сканирует assets/club → js/generated/club-images.js
 * Поддержка: .jpg .jpeg .png .webp (любой регистр)
 * Имя hero.* (без учёта регистра) помечается isHero: true
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CLUB_DIR = path.join(ROOT, "assets", "club");
const OUT_DIR = path.join(ROOT, "js", "generated");
const OUT_FILE = path.join(OUT_DIR, "club-images.js");
const EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

function isImage(name) {
  return EXT.has(path.extname(name).toLowerCase());
}

function isHeroName(name) {
  // hero.jpg / HERO.PNG / Hero.WebP и т.п.
  return path.parse(name).name.toLowerCase() === "hero";
}

function toSrc(filename) {
  return "assets/club/" + filename.split("/").map(encodeURIComponent).join("/");
}

function main() {
  fs.mkdirSync(CLUB_DIR, { recursive: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  let files = [];
  try {
    files = fs
      .readdirSync(CLUB_DIR, { withFileTypes: true })
      .filter((d) => d.isFile() && !d.name.startsWith(".") && isImage(d.name))
      .map((d) => d.name)
      .sort((a, b) => a.localeCompare(b, "ru", { sensitivity: "base" }));
  } catch (_) {
    files = [];
  }

  const images = files.map((f) => ({
    file: f,
    src: toSrc(f),
    alt: "ZAGA GAME — фото клуба",
    isHero: isHeroName(f)
  }));

  const body =
    "/* AUTO-GENERATED by scripts/generate-assets.js — не редактировать вручную */\n" +
    "window.CLUB_IMAGES = " +
    JSON.stringify(images, null, 2) +
    ";\n";

  fs.writeFileSync(OUT_FILE, body, "utf8");
  const hero = images.find((i) => i.isHero);
  console.log("[generate-assets] club images: " + images.length + (hero ? " (hero: " + hero.file + ")" : " (no hero.*)"));
  images.forEach((img) => console.log("  - " + img.file + (img.isHero ? " [HERO]" : "")));
}

main();
